# Generated by Django 3.2.12 on 2022-09-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='pur_date',
            field=models.DateField(verbose_name='Enroll Date (mm/dd/yyyy)'),
        ),
    ]
