# Generated by Django 3.2.12 on 2022-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220915_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
