# Generated by Django 3.2.12 on 2022-09-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='pur_date',
            field=models.DateTimeField(verbose_name='Enroll Date (yyyy/mm/dd)'),
        ),
    ]
